"""add googleId

Revision ID: 25de9e4a8673
Revises: 13afd73ec301
Create Date: 2025-02-25 18:49:15.771749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25de9e4a8673'
down_revision: Union[str, None] = '13afd73ec301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('google_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'account', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'google_id')
    # ### end Alembic commands ###
