name: Run tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Set environment variables
        env:
          PORT: ${{ secrets.PORT }}
          POSTGRESQL_USER: postgres
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          DATABASE_URL: postgresql://postgres:${{ secrets.POSTGRESQL_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENV: ${{ secrets.ENV }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          echo "PORT=${PORT}" >> $GITHUB_ENV
          echo "POSTGRESQL_USER=${POSTGRESQL_USER}" >> $GITHUB_ENV
          echo "POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}" >> $GITHUB_ENV
          echo "DATABASE_URL=${DATABASE_URL}" >> $GITHUB_ENV
          echo "JWT_SECRET=${JWT_SECRET}" >> $GITHUB_ENV
          echo "ENV=${ENV}" >> $GITHUB_ENV
          echo "DB_NAME=${DB_NAME}" >> $GITHUB_ENV

      - name: Run tests with pytest
        run: |
          pytest
