name: Run tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables from GitHub secrets
        run: |
          - echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          - echo "POSTGRESQL_USER=${{ secrets.POSTGRESQL_USER }}" >> $GITHUB_ENV
           - echo "POSTGRESQL_PASSWORD=${{ secrets.POSTGRESQL_PASSWORD }}" >> $GITHUB_ENV
          - echo "DATABASE_URL=postgresql://postgres:${{ secrets.POSTGRESQL_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          - echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          - echo "ENV=${{ secrets.ENV }}" >> $GITHUB_ENV
          - echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U ${{ secrets.POSTGRESQL_USER }}; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Run tests with pytest
        run: |
          pytest
